# Generated by Django 5.1.4 on 2024-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('balance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[("to'langan", "To'langan"), ('qarzdor', 'Qarzdor')], default="to'langan", max_length=20)),
            ],
        ),
    ]
