# Generated by Django 5.1.4 on 2024-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_balance', '0005_student_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default="to'langan", max_length=30),
        ),
    ]
